
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VPaned vpaned5;
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	private global::Gtk.TextView textview6;
	private global::Gtk.VBox vbox7;
	private global::Gtk.VBox vbox8;
	private global::Gtk.HButtonBox hbuttonbox6;
	private global::Gtk.Button button100;
	private global::Gtk.Button button101;
	private global::Gtk.Button button102;
	private global::Gtk.Button button103;
	private global::Gtk.Button button104;
	private global::Gtk.HButtonBox hbuttonbox7;
	private global::Gtk.Button button95;
	private global::Gtk.Button button96;
	private global::Gtk.Button button97;
	private global::Gtk.Button button98;
	private global::Gtk.Button button99;
	private global::Gtk.HButtonBox hbuttonbox8;
	private global::Gtk.Button button90;
	private global::Gtk.Button button91;
	private global::Gtk.Button button92;
	private global::Gtk.Button button93;
	private global::Gtk.Button button94;
	private global::Gtk.HPaned hpaned1;
	private global::Gtk.HButtonBox hbuttonbox5;
	private global::Gtk.Button button82;
	private global::Gtk.Button button83;
	private global::Gtk.Button button84;
	private global::Gtk.Button button86;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.Resizable = false;
		this.AllowGrow = false;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vpaned5 = new global::Gtk.VPaned ();
		this.vpaned5.CanFocus = true;
		this.vpaned5.Name = "vpaned5";
		this.vpaned5.Position = 66;
		// Container child vpaned5.Gtk.Paned+PanedChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.textview6 = new global::Gtk.TextView ();
		this.textview6.CanFocus = true;
		this.textview6.Name = "textview6";
		this.GtkScrolledWindow.Add (this.textview6);
		this.vpaned5.Add (this.GtkScrolledWindow);
		global::Gtk.Paned.PanedChild w2 = ((global::Gtk.Paned.PanedChild)(this.vpaned5 [this.GtkScrolledWindow]));
		w2.Resize = false;
		// Container child vpaned5.Gtk.Paned+PanedChild
		this.vbox7 = new global::Gtk.VBox ();
		this.vbox7.Name = "vbox7";
		this.vbox7.Spacing = 6;
		// Container child vbox7.Gtk.Box+BoxChild
		this.vbox8 = new global::Gtk.VBox ();
		this.vbox8.Name = "vbox8";
		this.vbox8.Spacing = 6;
		// Container child vbox8.Gtk.Box+BoxChild
		this.hbuttonbox6 = new global::Gtk.HButtonBox ();
		this.hbuttonbox6.Name = "hbuttonbox6";
		// Container child hbuttonbox6.Gtk.ButtonBox+ButtonBoxChild
		this.button100 = new global::Gtk.Button ();
		this.button100.WidthRequest = 85;
		this.button100.HeightRequest = 35;
		this.button100.CanFocus = true;
		this.button100.Name = "button100";
		this.button100.UseUnderline = true;
		this.button100.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
		this.hbuttonbox6.Add (this.button100);
		global::Gtk.ButtonBox.ButtonBoxChild w3 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox6 [this.button100]));
		w3.Expand = false;
		w3.Fill = false;
		// Container child hbuttonbox6.Gtk.ButtonBox+ButtonBoxChild
		this.button101 = new global::Gtk.Button ();
		this.button101.CanFocus = true;
		this.button101.Name = "button101";
		this.button101.UseUnderline = true;
		this.button101.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
		this.hbuttonbox6.Add (this.button101);
		global::Gtk.ButtonBox.ButtonBoxChild w4 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox6 [this.button101]));
		w4.Position = 1;
		w4.Expand = false;
		w4.Fill = false;
		// Container child hbuttonbox6.Gtk.ButtonBox+ButtonBoxChild
		this.button102 = new global::Gtk.Button ();
		this.button102.CanFocus = true;
		this.button102.Name = "button102";
		this.button102.UseUnderline = true;
		this.button102.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
		this.hbuttonbox6.Add (this.button102);
		global::Gtk.ButtonBox.ButtonBoxChild w5 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox6 [this.button102]));
		w5.Position = 2;
		w5.Expand = false;
		w5.Fill = false;
		// Container child hbuttonbox6.Gtk.ButtonBox+ButtonBoxChild
		this.button103 = new global::Gtk.Button ();
		this.button103.CanFocus = true;
		this.button103.Name = "button103";
		this.button103.UseUnderline = true;
		this.button103.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
		this.hbuttonbox6.Add (this.button103);
		global::Gtk.ButtonBox.ButtonBoxChild w6 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox6 [this.button103]));
		w6.Position = 3;
		w6.Expand = false;
		w6.Fill = false;
		// Container child hbuttonbox6.Gtk.ButtonBox+ButtonBoxChild
		this.button104 = new global::Gtk.Button ();
		this.button104.CanFocus = true;
		this.button104.Name = "button104";
		this.button104.UseUnderline = true;
		this.button104.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
		this.hbuttonbox6.Add (this.button104);
		global::Gtk.ButtonBox.ButtonBoxChild w7 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox6 [this.button104]));
		w7.Position = 4;
		w7.Expand = false;
		w7.Fill = false;
		this.vbox8.Add (this.hbuttonbox6);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.hbuttonbox6]));
		w8.Position = 0;
		w8.Expand = false;
		w8.Fill = false;
		// Container child vbox8.Gtk.Box+BoxChild
		this.hbuttonbox7 = new global::Gtk.HButtonBox ();
		this.hbuttonbox7.Name = "hbuttonbox7";
		// Container child hbuttonbox7.Gtk.ButtonBox+ButtonBoxChild
		this.button95 = new global::Gtk.Button ();
		this.button95.WidthRequest = 85;
		this.button95.HeightRequest = 35;
		this.button95.CanFocus = true;
		this.button95.Name = "button95";
		this.button95.UseUnderline = true;
		this.button95.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
		this.hbuttonbox7.Add (this.button95);
		global::Gtk.ButtonBox.ButtonBoxChild w9 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox7 [this.button95]));
		w9.Expand = false;
		w9.Fill = false;
		// Container child hbuttonbox7.Gtk.ButtonBox+ButtonBoxChild
		this.button96 = new global::Gtk.Button ();
		this.button96.CanFocus = true;
		this.button96.Name = "button96";
		this.button96.UseUnderline = true;
		this.button96.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
		this.hbuttonbox7.Add (this.button96);
		global::Gtk.ButtonBox.ButtonBoxChild w10 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox7 [this.button96]));
		w10.Position = 1;
		w10.Expand = false;
		w10.Fill = false;
		// Container child hbuttonbox7.Gtk.ButtonBox+ButtonBoxChild
		this.button97 = new global::Gtk.Button ();
		this.button97.CanFocus = true;
		this.button97.Name = "button97";
		this.button97.UseUnderline = true;
		this.button97.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
		this.hbuttonbox7.Add (this.button97);
		global::Gtk.ButtonBox.ButtonBoxChild w11 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox7 [this.button97]));
		w11.Position = 2;
		w11.Expand = false;
		w11.Fill = false;
		// Container child hbuttonbox7.Gtk.ButtonBox+ButtonBoxChild
		this.button98 = new global::Gtk.Button ();
		this.button98.CanFocus = true;
		this.button98.Name = "button98";
		this.button98.UseUnderline = true;
		this.button98.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
		this.hbuttonbox7.Add (this.button98);
		global::Gtk.ButtonBox.ButtonBoxChild w12 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox7 [this.button98]));
		w12.Position = 3;
		w12.Expand = false;
		w12.Fill = false;
		// Container child hbuttonbox7.Gtk.ButtonBox+ButtonBoxChild
		this.button99 = new global::Gtk.Button ();
		this.button99.CanFocus = true;
		this.button99.Name = "button99";
		this.button99.UseUnderline = true;
		this.button99.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
		this.hbuttonbox7.Add (this.button99);
		global::Gtk.ButtonBox.ButtonBoxChild w13 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox7 [this.button99]));
		w13.Position = 4;
		w13.Expand = false;
		w13.Fill = false;
		this.vbox8.Add (this.hbuttonbox7);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.hbuttonbox7]));
		w14.Position = 1;
		w14.Expand = false;
		w14.Fill = false;
		// Container child vbox8.Gtk.Box+BoxChild
		this.hbuttonbox8 = new global::Gtk.HButtonBox ();
		this.hbuttonbox8.Name = "hbuttonbox8";
		// Container child hbuttonbox8.Gtk.ButtonBox+ButtonBoxChild
		this.button90 = new global::Gtk.Button ();
		this.button90.WidthRequest = 85;
		this.button90.HeightRequest = 35;
		this.button90.CanFocus = true;
		this.button90.Name = "button90";
		this.button90.UseUnderline = true;
		this.button90.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
		this.hbuttonbox8.Add (this.button90);
		global::Gtk.ButtonBox.ButtonBoxChild w15 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox8 [this.button90]));
		w15.Expand = false;
		w15.Fill = false;
		// Container child hbuttonbox8.Gtk.ButtonBox+ButtonBoxChild
		this.button91 = new global::Gtk.Button ();
		this.button91.CanFocus = true;
		this.button91.Name = "button91";
		this.button91.UseUnderline = true;
		this.button91.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
		this.hbuttonbox8.Add (this.button91);
		global::Gtk.ButtonBox.ButtonBoxChild w16 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox8 [this.button91]));
		w16.Position = 1;
		w16.Expand = false;
		w16.Fill = false;
		// Container child hbuttonbox8.Gtk.ButtonBox+ButtonBoxChild
		this.button92 = new global::Gtk.Button ();
		this.button92.CanFocus = true;
		this.button92.Name = "button92";
		this.button92.UseUnderline = true;
		this.button92.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
		this.hbuttonbox8.Add (this.button92);
		global::Gtk.ButtonBox.ButtonBoxChild w17 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox8 [this.button92]));
		w17.Position = 2;
		w17.Expand = false;
		w17.Fill = false;
		// Container child hbuttonbox8.Gtk.ButtonBox+ButtonBoxChild
		this.button93 = new global::Gtk.Button ();
		this.button93.CanFocus = true;
		this.button93.Name = "button93";
		this.button93.UseUnderline = true;
		this.button93.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
		this.hbuttonbox8.Add (this.button93);
		global::Gtk.ButtonBox.ButtonBoxChild w18 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox8 [this.button93]));
		w18.Position = 3;
		w18.Expand = false;
		w18.Fill = false;
		// Container child hbuttonbox8.Gtk.ButtonBox+ButtonBoxChild
		this.button94 = new global::Gtk.Button ();
		this.button94.CanFocus = true;
		this.button94.Name = "button94";
		this.button94.UseUnderline = true;
		this.button94.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
		this.hbuttonbox8.Add (this.button94);
		global::Gtk.ButtonBox.ButtonBoxChild w19 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox8 [this.button94]));
		w19.Position = 4;
		w19.Expand = false;
		w19.Fill = false;
		this.vbox8.Add (this.hbuttonbox8);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.hbuttonbox8]));
		w20.Position = 2;
		w20.Expand = false;
		w20.Fill = false;
		this.vbox7.Add (this.vbox8);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.vbox8]));
		w21.Position = 0;
		w21.Expand = false;
		w21.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.hpaned1 = new global::Gtk.HPaned ();
		this.hpaned1.CanFocus = true;
		this.hpaned1.Name = "hpaned1";
		this.hpaned1.Position = 281;
		// Container child hpaned1.Gtk.Paned+PanedChild
		this.hbuttonbox5 = new global::Gtk.HButtonBox ();
		this.hbuttonbox5.Name = "hbuttonbox5";
		// Container child hbuttonbox5.Gtk.ButtonBox+ButtonBoxChild
		this.button82 = new global::Gtk.Button ();
		this.button82.WidthRequest = 85;
		this.button82.HeightRequest = 35;
		this.button82.CanFocus = true;
		this.button82.Name = "button82";
		this.button82.UseUnderline = true;
		this.button82.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
		this.hbuttonbox5.Add (this.button82);
		global::Gtk.ButtonBox.ButtonBoxChild w22 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox5 [this.button82]));
		w22.Expand = false;
		w22.Fill = false;
		// Container child hbuttonbox5.Gtk.ButtonBox+ButtonBoxChild
		this.button83 = new global::Gtk.Button ();
		this.button83.CanFocus = true;
		this.button83.Name = "button83";
		this.button83.UseUnderline = true;
		this.button83.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
		this.hbuttonbox5.Add (this.button83);
		global::Gtk.ButtonBox.ButtonBoxChild w23 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox5 [this.button83]));
		w23.Position = 1;
		w23.Expand = false;
		w23.Fill = false;
		// Container child hbuttonbox5.Gtk.ButtonBox+ButtonBoxChild
		this.button84 = new global::Gtk.Button ();
		this.button84.CanFocus = true;
		this.button84.Name = "button84";
		this.button84.UseUnderline = true;
		this.button84.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
		this.hbuttonbox5.Add (this.button84);
		global::Gtk.ButtonBox.ButtonBoxChild w24 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox5 [this.button84]));
		w24.Position = 2;
		w24.Expand = false;
		w24.Fill = false;
		this.hpaned1.Add (this.hbuttonbox5);
		global::Gtk.Paned.PanedChild w25 = ((global::Gtk.Paned.PanedChild)(this.hpaned1 [this.hbuttonbox5]));
		w25.Resize = false;
		// Container child hpaned1.Gtk.Paned+PanedChild
		this.button86 = new global::Gtk.Button ();
		this.button86.HeightRequest = 35;
		this.button86.CanFocus = true;
		this.button86.Name = "button86";
		this.button86.UseUnderline = true;
		this.button86.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
		this.hpaned1.Add (this.button86);
		this.vbox7.Add (this.hpaned1);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hpaned1]));
		w27.Position = 1;
		w27.Expand = false;
		w27.Fill = false;
		this.vpaned5.Add (this.vbox7);
		this.Add (this.vpaned5);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 472;
		this.DefaultHeight = 255;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
